name:                gr
version:             0.1.0.0
github:              "aupiff/gr"
license:             BSD3
author:              "Roy Blankman"
maintainer:          "riblankman@gmail.com"
copyright:           "2017 Roy Blankman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/gr#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  gr:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gr

tests:
  gr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gr
